# Site settings
title: "Inma Urena's resume"
description: "This site has been done with Jekyll "

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Inma Urena"
resume_title:                   "PhD, Lecturer at Universidad de Jaén"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "miurena[at]ujaen.es"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "-"
resume_contact_address:         "D2-208, Campus Las Lagunillas s/n, Jaén, Spain"

resume_header_contact_info:     "D2-208, Campus Las Lagunillas s/n, Jaén, Spain • miurena[at]ujaen.es"
display_header_contact_info:    "false"

resume_header_intro: "<p>Inmaculada Ureña Asensio (PhD, 2025) is Lecturer in English at the University of Jaén (Spain). Her research focuses on data modeling, digital scholarly editions and Thomas More studies. For her thesis dissertation, she has developed the project [A Digital Scholarly Edition of Utopia de Thomas Moro \(1637\)](http://utopiadethomasmoro-digitaledition.com/) encoded with TEI the Spanish translation of Thomas More’s <em>Utopia</em>. In 2023, she was PhD visiting research at Northeastern University (Boston, USA).</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      false
resume_section_education:       true
# publications was Associations before
resume_section_publications:    true
#conferences was projects before
resume_section_conferences:        true
# resume_section_skills:          false
# resume_section_recognition:     false
# resume_section_links:           false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/miurena"
  resume_twitter_url:           "http://twitter.com/inmaurena"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
